services:
  - type: web
    name: email-detection-api
    env: node
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 300
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: PROD_REDIRECT_URI
        value: "https://email-detection-api.onrender.com/api/gmail/callback"
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: "--max-old-space-size=768"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type,Authorization"
    # Static file handling
    staticPublishPath: ./public
    # Routes configuration
    routes:
      # API routes
      - type: rewrite
        source: /api/*
        destination: /api/$1
      # Auth routes with no rewrites
      - type: rewrite
        source: /login.html
        destination: /login.html
      - type: rewrite
        source: /signup.html
        destination: /signup.html
      # Explicit routes for HTML pages
      - type: rewrite
        source: /login
        destination: /login.html
      - type: rewrite
        source: /admin
        destination: /admin-dashboard.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      # Static assets
      - type: rewrite
        source: /css/*
        destination: /css/$1
      - type: rewrite
        source: /js/*
        destination: /js/$1
      # Fallback route for SPA - should be last
      - type: rewrite
        source: /*
        destination: /index.html
