services:
  - type: web
    name: email-detection
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
