services:
  - type: web
    name: email-detection
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 180
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
    domains:
      - email-detection-api.onrender.com
