services:
  - type: web
    name: email-detection-api
    env: node
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 300
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://chd-police-hackathon.vercel.app"
      - key: PROD_REDIRECT_URI
        value: "https://email-detection-api.onrender.com/api/gmail/callback"
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "https://chd-police-hackathon.vercel.app"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type,Authorization"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /auth/*
        destination: /auth/$1
      - type: rewrite
        source: /health
        destination: /health
