services:
  - type: web
    name: email-detection
    env: node
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 180
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: PROD_REDIRECT_URI
        value: "https://email-detection-api.onrender.com/api/gmail/callback"
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /login
        destination: /login.html
      - type: rewrite
        source: /admin
        destination: /admin-dashboard.html
      - type: rewrite
        source: /*
        destination: /index.html
